# Generated by Django 4.2 on 2024-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockvideo',
            name='gym_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rockvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rockvideo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
