# Generated by Django 4.2 on 2024-04-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb_app', '0003_vote_rockvideo_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='rockVideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_votes', to='rockclimb_app.rockvideo'),
        ),
    ]
