# Generated by Django 4.2 on 2024-04-08 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb_app', '0005_alter_vote_rockvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockvideo',
            name='votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='rockVideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rockclimb_app.rockvideo'),
        ),
    ]
