# Generated by Django 4.2 on 2024-04-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rockclimb_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rockclimb_app', '0006_remove_rockvideo_votes_alter_vote_rockvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockvideo',
            name='user',
            field=models.ForeignKey(default=rockclimb_app.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='rock_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
